global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: 'doplac-staging-log'
    send_resolved: true
