global:
 resolve_timeout: 1m
 slack_api_url: 'https://hooks.slack.com/services/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k'
 
route:
 receiver: 'slack-notifications'
 
receivers:
- name: 'slack-notifications'
 slack_configs:
 - channel: '#monitoring'
   send_resolved: true