version: '3'
networks:
  my-network:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - my-network

  node_exporter:
    image: prom/node-exporter
    hostname: node_exporter
    ports:
      - 9100:9100
    networks:
      - my-network

  alertmanager:
    image: prom/alertmanager
    hostname: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'
    networks:
      - my-network