version: 3
services:
 prometheus:
  image: prom/prometheus
  ports:
   - 9090:9090
 node-exporter:
  image: prom/node-exporter
  ports:
   - 9100:9100
 alert manager:
  image: prom/alertmanager
  ports:
   - 9093:9093