global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - rules/alert_rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
       - prometheus:9090

  - job_name: node_exporter
    static_configs:
    - targets:
       - node_exporter:9100